# Configuration file for "ballerinaproect"
# How to use see:
# https://ballerina.io/learn/provide-values-to-configurable-variables/#provide-via-toml-syntax


# "host" is an optional value
# host = ""	# Type of STRING

# "port" is an optional value
# port = 0	# Type of INTEGER

username = ""	# Type of STRING

password = ""	# Type of STRING

database = ""	# Type of STRING

